### ISSUE TITLE
where is the trained version of stage 1? 

### ISSUE THREAD

**Issue by wzhwzhwzh0921** [zyang1580/CoLLM#14]
https://xxxxx/. There is no pretrained model.

**Comment by zyang1580** [comment]
Thanks for your interest in our work. I will upload it this weekend if I have time. You could also train it yourself.

**Comment by mh-wu1001** [comment]
I'm trying to run your project but I've encountered an issue. In the configuration file, there's a path set for a pretrained model:
"/data2/zyang/minigpt4rec-log/0912_ml1m_oodv2_best_model_d256lr-0.001wd0.0001.pth"
I would appreciate it if you could upload this file to the repository or provide a download link for it. Alternatively, if there are instructions on how to generate this model, that would also be very helpful.

**Comment by zyang1580** [comment]
Link：https://rec.ustc.edu.cn/share/f7c20240-5fb1-11ef-acb4-298118b1826d  
The models are uploading the above link, you can find it later.

Notably, the saved model size is relatively large due to the repeated saving of the initial saving strategy. We have provided another version of the saving code, please refer to our [BinLLM repo](https://github.com/zyang1580/BinLLM).

**Comment by zyang1580** [comment]
> I'm trying to run your project but I've encountered an issue. In the configuration file, there's a path set for a pretrained model:
> 
> "/data2/zyang/minigpt4rec-log/0912_ml1m_oodv2_best_model_d256lr-0.001wd0.0001.pth"
> 
> I would appreciate it if you could upload this file to the repository or provide a download link for it. Alternatively, if there are instructions on how to generate this model, that would also be very helpful.

I will also upload the corresponding model.
